version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    # For production, add a volume to the web and nginx services in docker-compose.prod.yml so that each container will share a directory named "staticfiles"
    volumes:
      - static_volume:/home/app/web/staticfiles
    # replace with expose after confugire nginx
    # ports:
    #   - 8000:8000
    # Now, port 8000 is only exposed internally, to other Docker services. The port will no longer be published to the host machine.
    expose:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    # For production, add a volume to the web and nginx services in docker-compose.prod.yml so that each container will share a directory named "staticfiles"
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: